/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/snippets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single snippet by ID */
        get: operations["getSnippetById"];
        /**
         * Update a snippet
         * @description Updates the content of an existing thought snippet
         */
        put: operations["updateSnippet"];
        post?: never;
        /**
         * Delete a snippet
         * @description Permanently deletes a thought snippet
         */
        delete: operations["deleteSnippet"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all interests
         * @description Retrieves all saved interests with their snippet counts and weights
         */
        get: operations["getAllInterests"];
        put?: never;
        /**
         * Create an interest
         * @description Creates a new interest category with default beta-binomial prior (alpha=1, beta=1)
         */
        post: operations["createInterest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/{interestId}/snippets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get snippets for an interest
         * @description Retrieves all snippets categorized under the specified interest
         */
        get: operations["getSnippetsByInterest"];
        put?: never;
        /**
         * Create a snippet
         * @description Adds a new thought or quote under a specific interest
         */
        post: operations["createSnippet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/exposures/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record feedback for an exposure
         * @description Updates exposure reaction (keep, skip, explore) and shifts parent interest Beta distribution weights
         */
        post: operations["recordFeedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surface": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Surface a thought
         * @description Surfaces a thought snippet using Thompson Sampling bandit weights and 24h Redis recency suppression
         */
        get: operations["surface"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/interests/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an interest by ID */
        get: operations["getInterestById"];
        put?: never;
        post?: never;
        /**
         * Delete an interest
         * @description Deletes an interest and cascades deletion to all associated snippets
         */
        delete: operations["deleteInterest"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateSnippetRequest: {
            content: string;
        };
        SnippetResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            interestId?: string;
            interestName?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateInterestRequest: {
            name: string;
        };
        InterestResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            alpha?: number;
            /** Format: int32 */
            beta?: number;
            /** Format: int64 */
            snippetCount?: number;
            /** Format: date-time */
            createdAt?: string;
        };
        CreateSnippetRequest: {
            content: string;
        };
        FeedbackRequest: {
            reaction: string;
        };
        FeedbackResponse: {
            /** Format: uuid */
            exposureId?: string;
            reaction?: string;
            /** Format: date-time */
            respondedAt?: string;
            /** Format: uuid */
            interestId?: string;
            /** Format: int32 */
            updatedAlpha?: number;
            /** Format: int32 */
            updatedBeta?: number;
        };
        SurfaceResponse: {
            /** Format: uuid */
            exposureId?: string;
            /** Format: uuid */
            snippetId?: string;
            /** Format: uuid */
            interestId?: string;
            interestName?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSnippetById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnippetResponse"];
                };
            };
        };
    };
    updateSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSnippetRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnippetResponse"];
                };
            };
        };
    };
    deleteSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllInterests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterestResponse"][];
                };
            };
        };
    };
    createInterest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInterestRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterestResponse"];
                };
            };
        };
    };
    getSnippetsByInterest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interestId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnippetResponse"][];
                };
            };
        };
    };
    createSnippet: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                interestId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSnippetRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SnippetResponse"];
                };
            };
        };
    };
    recordFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedbackResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    surface: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully surfaced a thought */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SurfaceResponse"];
                };
            };
            /** @description No eligible thoughts available to surface */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SurfaceResponse"];
                };
            };
        };
    };
    getInterestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["InterestResponse"];
                };
            };
        };
    };
    deleteInterest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
