server:
  port: 8080

spring:
  application:
    name: rekindle

  datasource:
    url: jdbc:postgresql://localhost:5434/rekindle?options=-c%20timezone=UTC
    username: rekindle
    password: rekindle
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
